apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"web","namespace":"default"},"spec":{"replicas":200,"selector":{"matchLabels":{"app":"web"}},"template":{"metadata":{"labels":{"app":"web"}},"spec":{"containers":[{"image":"kubedevio/web-color:blue","name":"web","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}]}]}}}}
  creationTimestamp: "2024-12-29T03:47:04Z"
  generation: 4
  name: web
  namespace: default
  resourceVersion: "17704"
  uid: 3ace4b5e-0d3d-4150-8ac4-dd36a2cb0cda
spec:
  progressDeadlineSeconds: 600
  replicas: 200
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: kubedevio/web-color:blue
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 200
  conditions:
  - lastTransitionTime: "2024-12-29T03:47:04Z"
    lastUpdateTime: "2024-12-29T03:47:19Z"
    message: ReplicaSet "web-cc76c8c4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-29T04:27:41Z"
    lastUpdateTime: "2024-12-29T04:27:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 200
  replicas: 200
  updatedReplicas: 200
